const CREATION_SUCCESSFULL = 201
const OK = 200
const NO_CONTENT = 204

const NOT_FOUND = 404
const BAD_REQUEST = 400
const INVALID_TOKEN = 401
const FORBIDDEN_REQUEST = 403

const INTERNAL_SERVER_ERROR = 500
const DB_ERROR = 503

module.exports = {
  CREATION_SUCCESSFULL,
  OK,
  NO_CONTENT,
  NOT_FOUND,
  BAD_REQUEST,
  INVALID_TOKEN,
  FORBIDDEN_REQUEST,
  INTERNAL_SERVER_ERROR,
  DB_ERROR
}
